### ISSUE TITLE
How to use -s option

### ISSUE THREAD

**Issue by ojacques** [z37soft/INetSyphon_RaspberryPi_SDK#2]
Thanks for this awesome project. Given a spout feed of 640 * 3 (1920) * 480 which contains 3 screens of 640 x 480 each, side by side, how would I use tcpsclient to display screen 1 or 2 or 3 on the raspberry?
It seems that option `-s` (Source) is what i need. But I can’t see to be able to get it right. I was able to output screen 1 with `-s 0,0,0.333,1`.
But what about screen 2 and 3?
https://github.com/z37soft/INetSyphon_RaspberryPi_SDK/blob/master/RaspberryPi3_Stretch/main.cpp#L77

Thanks!

**Comment by ojacques** [comment]
Never mind, I figured it out!

With that type of spout feed:
```
+--------------------------------------------------------------------+
|                        |                     |                     |
|                        |                     |                     |
|                        |                     |                     |
|                        |                     |                     |
|     S C R E E N   1    |   S C R E E N   2   |   S C R E E N   3   |
|                        |                     |                     |
|                        |                     |                     |
|                        |                     |                     |
|                        |                     |                     |
|                        |                     |                     |
+--------------------------------------------------------------------+
```

-s is used for source with `-s left, top, right, bottom`, and range for parameters between 0 to 1 (float)

Which gives for each screen:
```
- screen 1: ./TCPSClient.bin -s 0    , 0, 0.333, 1
- screen 2: ./TCPSClient.bin -s 0.333, 0, 0.666, 1
- screen 3: ./TCPSClient.bin -s 0.666, 0, 1    , 1
```

There is a 2048x2048 limit also for the spout feed, TCPSClient with segfault above that value.

**Comment by ojacques** [comment]
@z37soft ^^

**Comment by z37soft** [comment]
Thank you for your report!
Sorry I'm moving from Singapore to Japan. so I sent my development environment also.
Since February I can develop again, if you can wait, then I will check it in Japan :-)
